name: Build and/or Release Flatpak

on:
  push:
    branches: ['**']  # Trigger on all branch pushes (including website commits)
    tags:
      - '*'  # Also trigger on tag pushes (e.g., v1.0.0)
  pull_request:  # Trigger on pull requests
  release:
    types: [created]  # Trigger on manual release creation

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to get full git history for changelog

    - name: Install Flatpak and dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y flatpak flatpak-builder
        flatpak remote-add --user --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

    - name: Build Flatpak
      run: |
        flatpak-builder --user --install-deps-from=flathub --force-clean --repo=.repo .build-dir org.freedownloadmanager.Manager.yaml
        flatpak build-bundle .repo org.freedownloadmanager.Manager.flatpak org.freedownloadmanager.Manager --runtime-repo=https://flathub.org/repo/flathub.flatpakrepo

    - name: Upload Flatpak bundle as artifact
      uses: actions/upload-artifact@v4
      with:
        name: freedownloadmanager-flatpak
        path: org.freedownloadmanager.Manager.flatpak

  release:
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Needed to get full git history for changelog

    - name: Generate changelog
      id: changelog
      run: |
        # Get all tags sorted by date
        TAGS=$(git tag --sort=-creatordate)
        # Get current tag
        CURR_TAG=$(git describe --tags)
        
        # Check if this is the first tag
        if [ $(echo "$TAGS" | wc -l) -eq 1 ]; then
          LOG=$(git log --reverse --pretty=format:"- %s (%h)")
        else
          PREV_TAG=$(echo "$TAGS" | sed -n 2p)
          LOG=$(git log "$PREV_TAG..$CURR_TAG" --reverse --pretty=format:"- %s (%h)")
        fi
        
        # Output the changelog
        echo "LOG<<EOF" >> $GITHUB_OUTPUT
        echo "$LOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Download build artifact
      uses: actions/download-artifact@v4
      with:
        name: freedownloadmanager-flatpak
        path: .

    - name: Create or Update Release
      uses: softprops/action-gh-release@v1
      with:
        files: org.freedownloadmanager.Manager.flatpak
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Changes since last release:
          ${{ steps.changelog.outputs.LOG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
