name: Dependency Update Check

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:     # Allow manual triggering

jobs:
  check-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests pyyaml

      - name: Run update script
        id: update
        run: python .github/scripts/update_dependencies.py

      - name: Create Pull Request
        if: env.CHANGES_MADE == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "chore: update dependencies"
          title: "Update Flatpak dependencies"
          body: |
            Automated update of Flatpak dependencies. Changes include:

            ${{ env.CHANGES_DETAILS }}

            This PR was automatically generated by GitHub Actions.
          branch: "dependency-updates"
          delete-branch: true
          labels: "dependencies,automated"
